apiVersion: v1
kind: PersistentVolume
metadata:
  name: chromadb-volume
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    type: DirectoryOrCreate
    path: /var/data/chroma
