apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chromadb-volume-claim
  namespace: lanflo-01
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
